import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

// TODO: Update metadata
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {/* Always show navigation and footer on all pages. */}
        <Navbar />
        {/* Add space so children are not covered by navbar. */}
        <div className='h-20' />
        {children}
        <Footer />
        <script async src='/dist/flowbite.min.js'></script>
      </body>
    </html>
  )
}
